@extends('layouts.admin')

@section('content')
    <div class="row mb-4">
        <div class="col-md-6">
            <h5 class="fw-bold mb-0">License Details</h5>
            <small class="text-muted">Detailed overview of key status and activation history.</small>
        </div>
        <div class="col-md-6 text-end">
            @if(auth()->user()->role !== 'client')
                <button class="btn btn-primary rounded-pill px-4 shadow-sm me-2" data-bs-toggle="modal"
                    data-bs-target="#renewModal">
                    <i class="fa fa-sync me-1"></i> Renew License
                </button>
            @endif
            <a href="{{ route('admin.licenses.index') }}" class="btn btn-light rounded-pill px-4 border shadow-sm">
                <i class="fa fa-arrow-left me-1 opacity-50"></i> Back to List
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <!-- License Info Card -->
            <div class="card border-0 shadow-sm mb-4">
                <div class="card-header bg-white py-3 border-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <h6 class="mb-0 fw-bold"><i class="fa fa-key me-2 text-primary-dark"></i> License Key Information
                        </h6>
                        @php
                            $statusClass = [
                                'active' => 'badge-active',
                                'expired' => 'badge-expired',
                                'suspended' => 'badge-suspended',
                                'revoked' => 'bg-secondary text-white',
                            ][$license->status] ?? 'bg-light text-dark';
                        @endphp
                        <span class="badge {{ $statusClass }} text-capitalize px-3">
                            {{ $license->status }}
                        </span>
                    </div>
                </div>
                <div class="card-body p-4 pt-0">
                    <div class="bg-light p-3 rounded-8 font-monospace text-center mb-4">
                        <h4 class="mb-0 text-primary-dark fw-bold text-break">{{ $license->license_key_display }}</h4>
                    </div>

                    <div class="row g-4">
                        <div class="col-md-4">
                            <label class="small text-muted d-block">Plan</label>
                            <span class="fw-bold">{{ $license->plan->name }}</span>
                        </div>
                        <div class="col-md-4">
                            <label class="small text-muted d-block">Owner</label>
                            <span class="fw-bold">{{ $license->owner->name }}</span>
                        </div>
                        <div class="col-md-4">
                            <label class="small text-muted d-block">Generated By</label>
                            <span class="fw-bold">{{ $license->generator->name }}</span>
                        </div>
                        <div class="col-md-4">
                            <label class="small text-muted d-block">Expires At</label>
                            <span
                                class="fw-bold {{ $license->expires_at && $license->expires_at->isPast() ? 'text-danger' : 'text-success' }}">
                                {{ $license->expires_at ? $license->expires_at->format('M d, Y') : 'Never' }}
                            </span>
                        </div>
                        <div class="col-md-4">
                            <label class="small text-muted d-block">Domain Limit</label>
                            <span class="fw-bold">{{ $license->max_domains }} Domains</span>
                        </div>
                        <div class="col-md-4">
                            <label class="small text-muted d-block">Created At</label>
                            <span class="fw-bold">{{ $license->created_at->format('M d, Y') }}</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Logs Card -->
            <div class="card border-0 shadow-sm">
                <div class="card-header bg-white py-3 border-0">
                    <h6 class="mb-0 fw-bold"><i class="fa fa-history me-2 text-primary-dark"></i> Activity History</h6>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0">
                            <thead class="bg-light text-muted small text-uppercase">
                                <tr>
                                    <th class="px-4 py-3">Timestamp</th>
                                    <th class="py-3">Action</th>
                                    <th class="py-3">User</th>
                                    <th class="py-3">Domain</th>
                                    <th class="px-4 py-3">IP Address</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($license->logs as $log)
                                    <tr>
                                        <td class="px-4 py-3 small text-muted">
                                            {{ $log->created_at->format('Y-m-d H:i') }}
                                        </td>
                                        <td class="py-3">
                                            <span class="badge bg-light text-dark text-capitalize">{{ $log->action }}</span>
                                        </td>
                                        <td class="py-3 small">
                                            {{ $log->user->name ?? 'System' }}
                                        </td>
                                        <td class="py-3 small">
                                            {{ $log->domain ?? '-' }}
                                        </td>
                                        <td class="px-4 py-3 small font-monospace">
                                            {{ $log->ip_address ?? '-' }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <!-- Activated Domains Card -->
            <div class="card border-0 shadow-sm mb-4">
                <div class="card-header bg-white py-3 border-0">
                    <h6 class="mb-0 fw-bold"><i class="fa fa-globe me-2 text-primary-dark"></i> Activated Domains</h6>
                </div>
                <div class="card-body p-0">
                    <ul class="list-group list-group-flush">
                        @forelse($license->domains as $domain)
                            <li class="list-group-item border-0 py-3 px-4 d-flex justify-content-between align-items-center">
                                <div>
                                    <h6 class="mb-0 fw-semibold">{{ $domain->domain_name }}</h6>
                                    <small class="text-muted">Since {{ $domain->activated_at->format('M d, Y') }}</small>
                                </div>
                                <form action="{{ route('admin.domains.destroy', $domain) }}" method="POST"
                                    onsubmit="return confirm('Deactivate this domain?')">
                                    @csrf @method('DELETE')
                                    <button type="submit" class="btn btn-light btn-sm rounded-circle shadow-sm">
                                        <i class="fa fa-times text-danger"></i>
                                    </button>
                                </form>
                            </li>
                        @empty
                            <li class="list-group-item border-0 p-4 text-center text-muted">
                                No domains activated yet.
                            </li>
                        @endforelse
                    </ul>
                </div>
                <div class="card-footer bg-white border-0 p-4 pt-0">
                    <div class="p-3 bg-light rounded-pill d-flex justify-content-between">
                        <span class="small fw-bold text-muted">Usage</span>
                        <span class="small fw-bold text-primary-dark">{{ $license->domains->count() }} /
                            {{ $license->max_domains }}</span>
                    </div>
                </div>
            </div>

            @if(auth()->user()->role !== 'client' && $license->status !== 'revoked')
                <div class="card border-0 shadow-sm">
                    <div class="card-body p-4">
                        <h6 class="fw-bold mb-3 font-small">Administrative Actions</h6>
                        <form action="{{ route('admin.licenses.revoke', $license) }}" method="POST"
                            onsubmit="return confirm('REVOKE this license? This is permanent.')">
                            @csrf
                            <button type="submit" class="btn btn-outline-danger w-100 rounded-pill">
                                <i class="fa fa-ban me-1"></i> Revoke License
                            </button>
                        </form>
                    </div>
                </div>
            @endif
        </div>
    </div>

    @if(auth()->user()->role !== 'client')
        <!-- Renew Modal -->
        <div class="modal fade" id="renewModal" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content border-0 shadow">
                    <form action="{{ route('admin.licenses.renew', $license) }}" method="POST">
                        @csrf
                        <div class="modal-header border-0 bg-light">
                            <h5 class="modal-title fw-bold">Renew License</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>
                        <div class="modal-body p-4">
                            <p class="text-muted small mb-4">Select a plan to extend the license expiration date. The quota will
                                be deducted if you are a distributor.</p>

                            <div class="mb-3">
                                <label class="form-label small fw-medium">Select Plan</label>
                                <select name="plan_id" class="form-select rounded-8" required>
                                    @foreach($plans as $plan)
                                        <option value="{{ $plan->id }}" {{ $license->plan_id == $plan->id ? 'selected' : '' }}>
                                            {{ $plan->name }} ({{ $plan->duration_days }} Days - {{ $plan->domain_limit }} Domains)
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="modal-footer border-0 p-4 pt-0">
                            <button type="button" class="btn btn-light rounded-pill px-4"
                                data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary rounded-pill px-4 shadow-sm">Renew Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endif
@endsection